5 create server
CA-G12/E-Commerce-Team3 pull request #9
Opened 2022-09-25 13:57 UTC by Saeed99Madi

2022-09-25 16:22 UTC, ysalem-dev-89 approved these changes

2022-09-25 18:32 UTC, shathakh requested changes

2022-09-25 18:32 UTC, shathakh commented on server/app.js
> +app.set('port', process.env.PORT);
here add a default port 
``` app.set('port', process.env.PORT || 7000); ```

2022-09-26 06:28 UTC, shathakh approved these changes

2022-09-26 06:33 UTC, nadasuhailAyesh12 approved these changes

2022-09-26 06:34 UTC, merged